Use reinterpret_cast instead of static_cast to cast NULL.
This fixes a build time error on Freebsd:
error: static_cast from 'nullptr_t' to 'gpr_atm' (aka 'long') is not allowed